---
- hosts: servers
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
  - name: Build the war file
    ansible.builtin.git:
      repo: https://github.com/devops4solutions/CI-usingAnsible.git
      clone: yes
      update: yes
    
  

    