---
- hosts: servers
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
  - name: create jenkins jobs with xml files    
    ansible.builtin.command: sudo java -jar jenkins-cli.jar -s http://localhost:8080  -auth dirsol:11e662e196a722e2d3a3d5514ef89707a8 install-plugin ansible:1.1