---
- hosts: servers
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: yum update
    yum:
      name: '*'
      state: latest
  
  - name:  install java-openjdk11
    ansible.builtin.command: sudo amazon-linux-extras install java-openjdk11 -y

  - name: Install Maven
    yum:
      name: maven
      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest
  
  - name: Install Git
    yum:
      name: git
      state: present
  
  - name: Install python jenkins
    ansible.builtin.command: python3 -m pip install python-jenkins   

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started

  - 
  - name: Download jenkins jar file
    ansible.builtin.get_url:
      url: http://localhost:8080/jnlpJars/jenkins-cli.jar
      dest: .
      mode: '0440'